<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>Custom.BlazorPdf.MudBlazor</PackageId>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <Version>1.0.0</Version>
        <Title>Custom.BlazorPdf.MudBlazor</Title>
        <Authors>armaanrustami</Authors>
        <Company>armaanrustami</Company>
        <Description>A simple, yet powerful Blazor PDF viewer (MudBlazor version)</Description>
        <Copyright>Custom.BlazorPdf OpenSource Apache-2.0</Copyright>
        <PackageIcon>logo.png</PackageIcon>
        <PackageProjectUrl>https://github.com/armaanrustami/blazor-pdf-viewer</PackageProjectUrl>
        <RepositoryUrl>https://github.com/armaanrustami/blazor-pdf-viewer</RepositoryUrl>
        <PackageTags>Blazor; MudBlazor; PDF</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RootNamespace>Custom.BlazorPdf.MudBlazor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
        <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.*"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*"/>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="MudBlazor" Version="9.10.0"/>
        <ProjectReference Include="../Custom.BlazorPdf/Custom.BlazorPdf.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="logo.png">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
